drop table if exists ss_user;
drop table if exists product;


CREATE TABLE product (
  id bigint generated by default as identity,
  name varchar(200),
  category_id bigint ,
  recommand varchar(500) ,
  status bigint  ,
  price DECIMAL(10,2)  ,
  merchant_id bigint ,
  url varchar(2000)  ,
  stock DECIMAL(10,0) ,
  primary key (id)
 );



create table ss_user (
	id bigint generated by default as identity,
	login_name varchar(64) not null unique,
	name varchar(64) not null,
	password varchar(255) not null,
	salt varchar(64) not null,
	roles varchar(255) not null,
	register_date timestamp not null,
	primary key (id)
);